version: "3.9"
services:

  db:
    image: "docker.io/library/mysql:5"
    environment:
      - "MYSQL_DATABASE=zabbix"
      - "MYSQL_PASSWORD=${ZABBIX_PASSWORD:?Need env: ZABBIX_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${ZABBIX_PASSWORD:?Need env: ZABBIX_PASSWORD}"
      - "MYSQL_USER=zabbix"
    command: ["docker-entrypoint.sh", "mysqld", "--character_set_server=utf8", "--collation_server=utf8_general_ci"]

  zabbix-web-nginx:
    image: "docker.io/zabbix/zabbix-web-nginx-mysql:${TAG:?Need env: TAG}"
    depends_on:
      - "db"
    environment:
      - "DB_SERVER_HOST=db"
      - "PHP_TZ=Europe/Oslo"
      - "MYSQL_DATABASE=zabbix"
      - "MYSQL_PASSWORD=${ZABBIX_PASSWORD:?Need env: ZABBIX_PASSWORD}"
      - "MYSQL_USER=zabbix"
      - "ZBX_SERVER_HOST=zabbix-server"
    ports:
      - "8080:8080"

  zabbix-server:
    image: "docker.io/zabbix/zabbix-server-mysql:${TAG:?Need env: TAG}"
    depends_on:
      - "db"
    environment:
      - "DB_SERVER_HOST=db"
      - "MYSQL_DATABASE=zabbix"
      - "MYSQL_PASSWORD=${ZABBIX_PASSWORD:?Need env: ZABBIX_PASSWORD}"
      - "MYSQL_USER=zabbix"
