version: "3.9"

volumes:
  mgmt:

services:
  mgmt:
    build: "./mgmt"
    volumes:
      - "mgmt:/mgmt"

  db:
    image: "docker.io/library/postgres:latest"
    environment:
      - "POSTGRES_DB=zabbix"
      - "POSTGRES_PASSWORD=${ZABBIX_PASSWORD:?Need env: ZABBIX_PASSWORD}"
      - "POSTGRES_USER=zabbix"

  zabbix-web-nginx:
    image: "docker.io/zabbix/zabbix-web-nginx-pgsql:${TAG:?Need env: TAG}"
    depends_on:
      - "db"
    environment:
      - "DB_SERVER_HOST=db"
      - "PHP_TZ=Europe/Oslo"
      - "POSTGRES_DB=zabbix"
      - "POSTGRES_PASSWORD=${ZABBIX_PASSWORD:?Need env: ZABBIX_PASSWORD}"
      - "POSTGRES_USER=zabbix"
      - "ZBX_SERVER_HOST=zabbix-server"
    ports:
      - "8080:8080"

  zabbix-server:
    image: "docker.io/zabbix/zabbix-server-pgsql:${TAG:?Need env: TAG}"
    depends_on:
      - "db"
      - "mgmt"
    environment:
      - "DB_SERVER_HOST=db"
      - "POSTGRES_DB=zabbix"
      - "POSTGRES_PASSWORD=${ZABBIX_PASSWORD:?Need env: ZABBIX_PASSWORD}"
      - "POSTGRES_USER=zabbix"
      - "ZBX_TLSCAFILE=/mgmt/ca/ca.cert.pem"
      - "ZBX_TLSCERTFILE=/mgmt/ca/ca.cert.pem"
      - "ZBX_TLSKEYFILE=/mgmt/ca/ca.key.pem"
    volumes:
      - "mgmt:/mgmt:ro"
