apiVersion: "v1"
kind: "Pod"
metadata:
  name: "zabbix-simple"
spec:
  containers:
    - image: "docker.io/library/postgres:latest"
      name: "postgres"
      env:
        - name: "POSTGRES_DB"
          value: "zabbix"
        - name: "POSTGRES_PASSWORD"
          value: "${ZABBIX_PASSWORD}"
        - name: "POSTGRES_USER"
          value: "zabbix"
      ports:
        - containerPort: 5432
          hostPort: 5432

    - image: "docker.io/zabbix/zabbix-server-pgsql:${TAG}"
      name: "zabbix-server"
      env:
        - name: "DB_SERVER_HOST"
          value: "localhost"
        - name: "POSTGRES_DB"
          value: "zabbix"
        - name: "POSTGRES_PASSWORD"
          value: "${ZABBIX_PASSWORD}"
        - name: "POSTGRES_USER"
          value: "zabbix"
      ports:
        - containerPort: 10051
          hostPort: 10051

    - image: "docker.io/zabbix/zabbix-web-nginx-pgsql:${TAG}"
      name: "zabbix-web"
      env:
        - name: "DB_SERVER_HOST"
          value: "localhost"
        - name: "PHP_TZ"
          value: "Europe/Oslo"
        - name: "POSTGRES_DB"
          value: "zabbix"
        - name: "POSTGRES_PASSWORD"
          value: "${ZABBIX_PASSWORD}"
        - name: "POSTGRES_USER"
          value: "zabbix"
        - name: "ZBX_SERVER_HOST"
          value: "localhost"
      ports:
        - containerPort: 8080
          hostPort: 8080

    - image: "docker.io/rroemhild/test-openldap"
      name: "ldap"
      ports:
        - containerPort: 10389
          hostPort: 10389
